### PR TITLE
Use psr-11 in composer.json

### PR DESCRIPTION
**Pull request by prisis**

### CODE REVIEW

**Comment by mnapoli** [comment]
Thanks!

**Comment by prisis** [comment]
Can you tag a new release?

**Comment by moufmouf** [comment]
Shouldn't we merge #34 before tagging that release?

**Comment by mnapoli** [comment]
@moufmouf I'm :+1: to merge it

**Comment by prisis** [comment]
@gbprod can you rebase #34? :)

**Comment by gbprod** [comment]
@prisis Done ;)

**Comment by moufmouf** [comment]
@prisis The README.md file still contains references to the old `Interop\Container\ContainerInterface`.
Would you mind opening a new PR to fix those before we tag a new release?

**Pull request merged**
