### PR TITLE
Completing composer.json

### PR DESCRIPTION
**Pull request by moufmouf**
In particular, added "name" and "autoload" section to be able to use the package.

### CODE REVIEW

**Comment by mnapoli** [comment]
:+1: maybe we should open another issue to discuss the name? I'm not a big fan of it, but I have trouble coming up with something better that is still explicit…

**Comment by moufmouf** [comment]
Actually, I like the name pretty much.
I don't think I can find any better name.
Of course, I'd like to replace that "service" part with something more generic, but I don't think that "entry-provider" would be as explicit for most of the PHP developers out there.

**Comment by mnapoli** [comment]
true. OK to register it on Packagist then?

**Comment by moufmouf** [comment]
I'd say yes!
I have a bunch of questions however (particularly regarding the use of "static" interfaces), but I'll open that in a separate thread.

**Comment by mnapoli** [comment]
:+1:

**Pull request merged**
